site_name: Linear Algebra Done Right 4th edition
theme: readthedocs

nav:
  - Home: index.md
  - Chapter 01 Notes: ch01notes.md
  - Chapter 01 Exercises: ch01ex.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math:
        enable_dollar_delimiter: True

repo_name: Github
repo_url: https://github.com/eroicaleo/liner-algebra-done-right-4th/
edit_uri: 'blob/main/docs/'
